-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Wersja serwera:               10.6.4-MariaDB - mariadb.org binary distribution
-- Serwer OS:                    Win64
-- HeidiSQL Wersja:              11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Zrzut struktury bazy danych starsdb
CREATE DATABASE IF NOT EXISTS `starsdb` /*!40100 DEFAULT CHARACTER SET utf8mb3 */;
USE `starsdb`;

-- Zrzut struktury tabela starsdb.constellations
CREATE TABLE IF NOT EXISTS `constellations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `declination` float NOT NULL DEFAULT 0,
  `symbolism` text NOT NULL,
  `sky_side` varchar(50) NOT NULL DEFAULT '',
  `area` float NOT NULL DEFAULT 0,
  `rectascension` float NOT NULL DEFAULT 0,
  `picture` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=229 DEFAULT CHARSET=utf8mb3;

-- Zrzucanie danych dla tabeli starsdb.constellations: ~88 rows (około)
DELETE FROM `constellations`;
/*!40000 ALTER TABLE `constellations` DISABLE KEYS */;
INSERT INTO `constellations` (`id`, `name`, `declination`, `symbolism`, `sky_side`, `area`, `rectascension`, `picture`) VALUES
	(141, 'Hydry', -20, 'Hydra, rozpościerając się na czwartej części nieba od Raka do Centaura, jest największym z gwiazdozbiorów, ale znaleźć ją niełatwo. Przy dobrych warunkach można raczej bez trudu odszukać na południe od Raka asteryzm „głowy”, złożony z gwiazd trzeciej i czwartej wielkości, ale reszta powyginanej grupy to niewiele więcej niż wstążka bladych punkcików.', 'south', 1303, 10, '.png'),
	(142, 'Panny', 0, 'Gwiazdy konstelacji, umieszczonej niemal prostopadle do Galaktyki, są blade i dostrzec je można tylko na bardzo ciemnym niebie. Centralny trapez utworzony przez Alfę, Zetę, Deltę i Gammę jest najłatwiej rozróżnialną częścią Panny. Spica, Porrima, Vindemiatrix oraz Zavijava tworzą charakterystyczny kształt litery Y.', 'north', 1294, 13, '.png'),
	(143, 'Wielka Niedźwiedzica', 55, 'Najjaśniejszą gwiazdą w tym gwiazdozbiorze jest ? UMa (Alioth), o jasności zmiennej od 1,68 do 1,78m. Siedem wyraźnych gwiazd tworzy znany asteryzm Wielkiego Wozu. Gwiazdy Wielkiego Wozu, z wyjątkiem Alkaida i Dubhe, przemieszczają się w przestrzeni razem. Towarzyszą im w tej wędrówce inne gwiazdy tego rejonu nieba. tworzą one tzw. Strumień Niedźwiedzicy, czyli gromadę gwiazd poruszających się w tym samym kierunku. Gwiazdozbiór ukazuje wyraźny obraz niedźwiedzia z dziwnie długim ogonem.', 'north', 1280, 1, '.png'),
	(144, 'Wieloryba', 10, 'Chociaż gwiazdozbiór jest ogromny, to jest w nim niewiele jasnych gwiazd. Nie ma tam żadnej gwiazdy pierwszej wielkości, a tylko jedna jest drugiej wielkości. Gwiazdy Alfa, Gamma i Delta tworzą przy zachodnim krańcu Wieloryba trójkąt, dający się łatwo zidentyfikować, poza tym niebo w tej okolicy jest w zasadzie puste. Omawiane trzy gwiazdy oraz liczne bledsze są tylko ledwo podobne do jakiegokolwiek stworzenia morskiego.', 'north', 1231, 2, NULL),
	(145, 'Herkulesa', 30, 'W konstelacji nie ma jasnych gwiazd, ale jest tam charakterystyczna grupa: Epsilon, Zeta, Eta i Pi, zwana Keystone (Zwornikiem). Łańcuchy gwiazd prowadzące z każdego narożnika oznaczają członki i głowę bohatera.', 'north', 1225, 17, NULL),
	(146, 'Erydanu', -25, 'W czasach nowożytnych na jednym końcu rzeki jest Alfa Erydanu, czyli Achernar (arab. „koniec rzeki”), drugi koniec wyznacza Beta Erydanu, nazywana też Cursa („podnóżek”), leżąca obok Rigela w Orionie. Achernar jest dziewiątą gwiazdą pod względem jasności na niebie. Jest to gorący niebieski olbrzym typu B,prawie sześć razy cięższy i pięć tysięcy razy jaśniejszy od Słońca.', 'south', 1138, 4, NULL),
	(147, 'Pegaza', 20, 'Trzy spośród najjaśniejszych gwiazd konstelacji, wraz z Alfa Andromedae, \nktóra wcześniej (jako Delta Pegasi) należała do Pegaza, tworzą obszerny \nWielki Kwadrat Pegaza, znany też jako „kwadrat jesienny”, a wraz z pozostałymi dwiema \nnajjaśniejszymi gwiazdami Andromedy układają się w kształt podobny do Wielkiego Wozu.', 'north', 1121, 23, NULL),
	(148, 'Smoka', 65, 'Mimo że to jeden z najstarszych i największych gwiazdozbiorów, nie jest szczególnie wyraźny.\nNajjaśniejsze gwiazdy konstelacji mają wielkość gwiazdową rzędu 2m. Bardzo charakterystyczną cechą\nSmoka jest wyraźny łuk biegnący między Małą i Wielką Niedźwiedzicą – zakończony głową smoka utworzoną\nz gwiazd Rastaban, Eltanin, Kuma i Grumium, mały czworobok w pobliżu Liry.', 'north', 1083, 15, NULL),
	(149, 'Centaura', -50, 'Centaur to wielka konstelacja, a jej gwiazdy całkiem przekonywająco odwzorowują centaura, \nktóry owija przednie i tylne nogi wokół Krzyża Południa. \nAlfa i Beta Centauri są przednimi kopytami centaura, a jednocześnie wskazują Krzyż Południa.', 'south', 1060, 13, NULL),
	(150, 'Wodnika', -13, 'Ogólnie gwiazdy Wodnika są raczej blade, tylko dwie z nich są jaśniejsze niż trzeciej wielkości gwiazdowej. \nNajlepiej rozpoznawalna jest grupa gwiazd tworząca „dzban z wodą”, znajdująca się w południowo-wschodniej\nczęści konstelacji, a składająca się z gwiazd piątej i szóstej wielkości. Choć są blade, to wyraźnie je widać na ciemnym niebie.', 'south', 979, 22, NULL),
	(151, 'Wężownika', -8, 'Wyraźny gwiazdozbiór znajdujący się w rejonie równika niebieskiego. Polsce najlepiej jest widoczny latem. Jest jedną z konstelacji ptolemejskich.', 'south', 948, 17, NULL),
	(152, 'Lwa', 15, 'W odróżnieniu od wielu innych gwiazdozbiorów Lew naprawdę przypomina swój pierwowzór. \nGłowę lwa reprezentuje skierowany do tyłu znak zapytania, asteryzm zwany Sierpem, złożony z sześciu\ngwiazd od Epsilon do Alfa Leonis. Wyraźny trójkąt prostokątny jest zadem lwa, a linie gwiazd - \nnogami wylegującej się bestii. Gwiazda Denebola (Leo) wyznacza jego ogon. Gromada gwiazd \nWarkocza Bereniki reprezentuje kosmyk na końcu ogona.', 'north', 946, 11, NULL),
	(153, 'Wolarza', 30, 'Najstarsze źródło, w którym podana jest nazwa tego gwiazdozbioru, to „Odyseja” Homera. \nZapis z dierezą nad drugim o ma wskazywać, że samogłoski te wymawia się oddzielnie. Inną grecką nazwą \njest Arktofilaks, „strażnik niedźwiedzia”; jest ona o tyle trafniejsza, że wraz z obrotem sfery niebieskiej \nWolarz podąża za Wielką Niedźwiedzicą. Pochodzi od niej także nazwa najjaśniejszej gwiazdy konstelacji, Arktura.', 'north', 907, 15, NULL),
	(154, 'Ryb', 15, 'Ryby są jednym z najbledszych gwiazdozbiorów Zodiaku. Jedynie dwie gwiazdy czwartej wielkości zdobią tę konstelację, \nTworzącą bardzo wydłużone V na południowy wschód od Wielkiego kwadratu Pegaza. asteryzm znany jako „Diadem” –\npięciokąt gwiazd czwartej i piątej wielkości, stworzony z gammy, tety, joty, kappy i lambdy to najbardziej rozpoznawalny fragment\ngwiazdozbioru, znajduje się dokładnie na południe od Wielkiego Kwadratu Pegaza. Stanowi ciało jednej z ryb – południowej.\nW jego wnętrzu leży TX Piscium (19 Piscium), czerwony olbrzym o ciemnopomarańczowej barwie, zmieniający jasność nieregularnie. \nObserwowana zmienność jasności waha się między 4,79 a 5,20m.', 'north', 889, 0, NULL),
	(155, 'Strzelca', -25, 'Osiem najjaśniejszych gwiazd tej konstelacji tworzą rozpoznawalny asteryzm zwany Imbrykiem, \nkształtem przypominający czajnik. Można go zobaczyć bez trudu nawet przy niezbyt czystym niebie.\nRączkę imbryka tworzą Tau , Fi , Zeta  i Sigma , jego wieczko Fi, Lambda  i Delta, podstawę\nZeta i Epsilon, natomiast dziobek Epsilon i Gamma.  Gwiazdy Lambda, Delta i Epsilon tworzą łuk.\nNatomiast Gamma wyznacza grot strzały.', 'south', 867, 19, NULL),
	(156, 'Łabędzia', 40, 'Ponieważ przez konstelację przechodzi Droga Mleczna, widać tam zatrzęsienie gwiazd – nic dziwnego, że jest to miejsce \nintensywnych badań astronomicznych. W szczególności teleskop Keplera prowadzi w tym rejonie obserwacje w celu \nposzukiwania planet pozasłonecznych wśród około 150 tysięcy gwiazd. Jaśniejsze gwiazdy tworzą asteryzm Krzyża Północy. \nTe same gwiazdy wraz z bledszymi – wypełniającymi skrzydła – układają się w łabędzia. Delta i Epsilon Cygni to jego skrzydła, \nmiędzy nimi znajduje się Gamma Cygni, Albireo tuż u końca szyi, Deneb zaś tam, gdzie ma on kuper. \nWymienione gwiazdy są jednocześnie pięcioma najjaśniejszymi w konstelacji.', 'north', 804, 21, NULL),
	(157, 'Byka', 15, 'Gwiazdy Byka są w większości blade. Poza ułożonymi w kształt litery V Hiadami, \nktóre tworzą wyraźny pysk, i dwoma rogami – betą i zetą – reszta wygląda jak byk atakujący Oriona.', 'north', 797, 5, NULL),
	(158, 'Żyrafy', 70, 'Osiem gwiazd o wielkości od 4,0 do 4,8m obrysowuje delikatną figurę przypominającą żyrafę. \nZnalezienie właściwych gwiazd utrudnia spora ilość innych, niewiele ciemniejszych, które migocą \nw tle tego gwiazdozbioru, szczególnie w jego południowej części, znajdującej się w Drodze Mlecznej.', 'north', 757, 6, NULL),
	(159, 'Andromedy', 40, 'Konstelację Andromedy bardzo łatwo można znaleźć na jesiennym niebie, gdyż jej gwiazdy leżą praktycznie w jednej linii.\n Główne gwiazdy Andromedy tworzą wydłużoną literę V, przy czym najjaśniejsze z nich mieszczą się w południowym ramieniu. \nWierzchołkiem litery V jest Alfa, która chociaż należy do Andromedy, to służy też jako narożnik Wielkiego Kwadratu Pegaza.', 'north', 722, 1, NULL),
	(160, 'Rufy', -40, 'Cztery najjaśniejsze gwiazdy w polu tej konstelacji mają jasność w przedziale 2,2 – 3m i są to kolejno: Naos , Pi Puppis, Ksi Puppis i L Pup.', 'south', 673, 8, NULL),
	(161, 'Woźnicy', 40, 'Najjaśniejsze gwiazdy tworzą pięciokąt, chociaż wysunięta najdalej na południe gwiazda tej figury od starożytności jest dzielona \nz Bykiem (należy „graficznie” do obu gwiazdozbiorów), a zawodowi astronomowie oficjalnie przyznali ją Bykowi.', 'north', 657, 6, NULL),
	(162, 'Orła', 3, 'Wiele gwiazd konstelacji jest bardzo bladych i trzeba sporo wyobraźni, by połączyć je w figurę. \nAlfa mająca z boków Betę i Gammę stanowią łatwo rozpoznawalną grupę, \ntworzącą szyję i głowę orła. Zeta i Epsilon stanowią koniec jednego skrzydła, \nTheta tworzy drugie, a Lambda – ogon.', 'north', 652, 20, NULL),
	(163, 'Węża', -8, 'Gwiazdy Węża są jednorodne, umiarkowanie blade, ale mały trójkąt utworzony przez gwiazdy czwartej wielkości Betę, \nGammę i Kappę wraz z Deltą, Alfą i Epsilonem, które tworzą szyję, są łatwe do znalezienia przy sprzyjających warunkach obserwacji.\nResztę figury trudno odróżnić od sąsiednich konstelacji.', 'south', 636, 17, NULL),
	(164, 'Perseusza', 45, 'Wyobrażany jako postać rycerza z mieczem w prawej ręce a głową Meduzy – oznaczonej przez słynną gwiazdę zmienną Algol – w drugiej.\nGwiazdozbiory mitologicznie z nim powiązane to również Andromeda, Kasjopeja, \nCefeusz, Pegaz oraz Wieloryb. Algol jest typowym przedstawicielem gwiazd zmiennych zaćmieniowych, złożonych z jasnego białego\nkarła oraz chłodniejszego podolbrzyma, w których obserwuje się okresowe osłabienie jasności.', 'north', 615, 4, NULL),
	(165, 'Kasjopei', 60, 'W 1572 roku w pobliżu gwiazdy Kappa Cassiopeiae nastąpił jeden z trzech wybuchów supernowej zaobserwowanych \nw naszej Galaktyce, opisany przez Tychona Brahe. Odległa o 7500 lat świetlnych gwiazda, obecnie o jasności 19m, nazwana na \njego cześć Supernową Tychona, rozbłysła wówczas do ?4,0m. Pozostałości tej supernowej do dziś emitują fale radiowe. Inna \nsupernowa, z roku 1660, która pozostała niezauważona przez ówczesnych obserwatorów, \npozostawiła najsilniejsze radioźródło na niebie, znane jako Cassiopeia A.', 'north', 598, 1, NULL),
	(166, 'Oriona', 0, 'Gwiazdozbiór zawiera wiele obszarów z materią międzygwiazdową oraz młode masywne gwiazdy, które tworzą regiony gwiazdotwórcze.\nTrzy ułożone w jednej linii jasne gwiazdy, tworzące asteryzm tzw. Pas Oriona wskazują Syriusza na południowym wschodzie i \nAldebarana na północnym zachodzie. Są to Delta (Mintaka), Epsilon (Alnilam) i Zeta Orionis (Alnitak).', 'north', 594, 5, NULL),
	(167, 'Cefeusza', 70, 'Cefeusz jest obramowany cienkim pięciokątem, trochę przypominającym dziecięcy rysunek konia. Trzeba być uważnym, \nbo cztery gwiazdy tworzące podstawę pięciokąta mogą też zostać użyte do stworzenia niemal identycznej figury, \nktóra zawierałaby również gwiazdę z gwiazdozbioru Smoka.', 'north', 588, 22, NULL),
	(168, 'Rysia', 50, 'Szukając tej konstelacji, obserwatorzy amatorzy zazwyczaj zaczynają od punktów startowych \nw jednym z sąsiednich jaśniejszych gwiazdozbiorów Wielkiej Niedźwiedzicy, Bliźniąt albo Woźnicy. \nNa przykład gromadę kulistą NGC 2419 można łatwo znaleźć, zaczynając obserwację od jasnego Kastora w Bliźniętach.', 'north', 545, 8, NULL),
	(169, 'Wagi', -15, 'Są w większości blade, ale kwadratowy kształt tworzony przez główne gwiazdy jest łatwy do znalezienia.\nLinia ciągnąca się od Alfy do Bety tworzy ramię wagi, a Gamma i Sigma kształtują dwie szalki. \nGwiazd Alfa i Beta zostały przeniesione ze Skorpiona w czasach rzymskich, a trzecią pod względem jasności sigmę „zabrano” dopiero w XIX wieku.', 'south', 538, 15, NULL),
	(170, 'Bliźniąt', 20, 'Jest to jedna z najłatwiejszych do znalezienia konstelacji. Dwie niemal jednakowo jasne gwiazdy Kastor i \nPolluks oznaczają głowy bliźniaków. Łatwo widzialna linia gwiazd wiodąca przez Kappę, Deltę, Zetę i Gammę \ntworzą ciało Polluksa. Równoległa linia gwiazd od jasnego Kastora poprzez gwiazdy trzeciej i czwartej wielkości Tau, Epsilon, Mi, Eta znaczą ciało Kastora.', 'north', 514, 7, NULL),
	(171, 'Raka', 20, 'Rak jest najbledszym z gwiazdozbiorów zodiaku. Z miast i z większości przedmieść nawet na ciemnym niebie wygląda po prostu jak \npuste miejsce pomiędzy gwiazdozbiorami Bliźniąt i Lwa. Nie jest spektakularny, a jego gwiazdy piątej i szóstej wielkości niezbyt \nprzypominają raka. Interesujące są Gamma i Delta Raka, leżące w pobliżu centrum, noszące łacińskie nazwy Asellus Borealis \ni Asellus Australis, czyli „osioł północny” i „osioł południowy”.', 'north', 506, 9, NULL),
	(172, 'Żagla', -50, 'Gwiazdozbiór Argo był bardzo rozległy, tak że astronomom zabrakło liter greckiego Alfabetu do oznaczenia jego gwiazd i musieli wykorzystać\nAlfabet łaciński. Wiele gwiazd znajdujących się w konstelacji jest oznaczonych literami pochodzącymi z Alfabetu łacińskiego. Kiedy gwiazdozbiór \nArgo został podzielony, przypisany przez Johanna Bayera porządek gwiazd nie został zmieniony bez względu na to, do którego z gwiazdozbiorów \ntrafiła dana gwiazda. Z tego powodu konstelacja nie ma gwiazdy Alfa ani gwiazdy Beta. Najjaśniejszą jest Gamma. Gwiazdy Żagla są dość jasne, \nale nie przypominają żagli, poza – ale i to nie za bardzo – żaglem rejowym. Dwie najlepiej znane gwiazdy to Kappa i Delta, tworzące z Epsilonem \ni Jotą Kila północną połówkę wyraźnego asteryzmu „Fałszywego Krzyża”, mylącego dawnych żeglarzy mórz południowych.', 'south', 500, 9, NULL),
	(173, 'Skorpiona ', -35, 'Tak jak w przypadku Strzelca również w Skorpionie nazwy Bayera nie odtwarzają porządku jasności gwiazd. \nNa przykład drugą co do jasności gwiazdą po Alfie jest Lambda. W centrum Skorpiona świeci na czerwono \nAntares, będący środkiem skorpiona. Ogon stanowi pokręcona linia gwiazd biegnąca poprzez Tau, Epsilona, Mi, \nZetę, Etę, Thetę, Jotę i Kappę, a Lambda i Ypsilon tworzą kolec na końcu ogona. Natomiast w bardziej współczesnych \nwersjach kleszcze skierowane w stronę głowy skorpiona są ukształtowane przez nieco zagiętą linię gwiazd: Ni, Betę i Deltę z jednej \nstrony oraz Pi i Ro z drugiej. Jednak tę konstelację można sobie wyobrazić jeszcze inaczej, jak to czynili Grecy: użyć Alfy i Bety Wagi i zobaczyć w pełni rozciągnięte kleszcze.', 'south', 497, 17, NULL),
	(174, 'Kila', -60, 'Argo była największą ze wszystkich konstelacji; Kil jest rozległą grupą przypominającą nieco kadłub greckiego statku. \nWschodni kraniec gwiazdozbioru zanurza się w Drodze Mlecznej. Gwiazd jaśniejszych niż 3m w tej konstelacji jest sześć: Kanopus, Miaplacidus, Avior, Aspidiske i ? Car.', 'south', 494, 9, NULL),
	(175, 'Jednorożca', -5, 'Chociaż gwiazdozbiór znajduje się ściśle na Drodze Mlecznej, to nie ma w nim jasnych gwiazd. Alfa i Beta leżą \nw środkowej strefie czwartej wielkości, a pozostałe gwiazdy są piątej wielkości lub słabsze. Nawet przy idealnie \nciemnym niebie nie można dostrzec w tych gwiazdach jakiegokolwiek podobieństwa do bajkowego jednorożca. \nTło Drogi Mlecznej jest w Jednorożcu dużo bledsze niż w większości innych miejsc, ponieważ tutaj patrzymy na zewnątrz, w kierunku krawędzi naszej galaktyki.', 'south', 482, 7, NULL),
	(176, 'Rzeźbiarza', -30, 'Gwiazdy Rzeźbiarza wyglądają jak przypadkowy zbiór bladych światełek, nie przypominający żadnego wizerunku. Alfa, Beta i Gamma są czwartej wielkości, a Delta prezentuje sobą gwiazdę piątej wielkości.', 'south', 475, 1, NULL),
	(177, 'Feniksa', -50, 'Są blade, ale wyraźnie tworzą zarys startującego ptaka widzianego od przodu. Jasna Alfa oznacza głowę, a Beta, Zeta, Eta i Epsilon \ntworzą resztę korpusu. Natomiast Gamma i Delta tworzą jedno skrzydło, a ciemna Jota i Theta to drugie skrzydło. Trio w kształcie \nkija golfowego złożone z Alfy, Kappy i Epsilona tworzy najwyraźniejszy asteryzm konstelacji.', 'south', 469, 1, NULL),
	(178, 'Psów \nGończych ', 40, 'W tym gwiazdozbiorze są tylko dwie wyraźne gwiazdy, Alfa i Beta Psów Gończych. Przedstawiają dwa psy o imionach Asterion i Chara, ale wśród astronomów nie ma zgody co \ndo tego, która gwiazda miała reprezentować którego psa. Alfa jest nazywana Cor Caroli („serce Karola”) od czasu przywrócenia monarchii brytyjskiej, kiedy Karol II odzyskał tron \nodebrany jego ojcu. Większość źródeł twierdzi, że Cor Caroli odnosi się do ściętego króla Karola I, ale są też i takie, które mówią o jego synu Karolu II. Cor Caroli jest to słynna gwiazda podwójna o szeroko rozdzielonych składnikach, zabarwionych na niebiesko i zielonkawo.', 'north', 465, 13, NULL),
	(179, 'Barana', 20, 'Układ najjaśniejszych gwiazd w Baranie tworzy charakterystyczny łuk, na który składają się: Hamal, Sheratan oraz Mesarthim.  \nWokół najjaśniejszej gwiazdy Hamal, czerwonego olbrzyma, krąży odkryta w 2011 roku egzoplaneta wielkości Jowisza.  Pokazowym obiektem konstelacji jest \nGamma Arietis, znana także jako Mesarthim, która była też nazywana pierwszą gwiazdą w Baranie. Jest to gwiazda podwójna, położona w odległości 204 lat świetlnych od Słońca, \nz niemal idealnie dopasowanymi gwiazdami typu spektralnego A i B, które – co dziwne – wydają się bladożółte. Już przez 10-centymetrowy teleskop są dobrze widoczne.', 'north', 441, 3, NULL),
	(180, 'Koziorożca', -20, 'Chociaż z trudem można zauważyć podobieństwo gwiazdozbioru do kozła (nawet z rybim ogonem), to gwiazdy \nKoziorożca względnie łatwo można odnaleźć na niebie. Większe z nich tworzą duży trójkąt, którego wierzchołki wyznaczają \nDwie gwiazdy czwartej wielkości Alfa i Omega oraz Delta, gwiazda trzeciej wielkości. Żadna z nich nie jest specjalnie jasna, ale przypomina bardzo kształt dolnej części bikini.', 'south', 414, 21, NULL),
	(181, 'Pieca', -30, 'Jak wiele z wynalazków Lacaille’a gwiazdy Pieca nie bardzo przypominają figurę związaną z nazwą konstelacji i nie przyciągają specjalnej uwagi obserwatorów. Nie zawiera gwiazd powyżej 4 wielkości.', 'south', 398, 3, NULL),
	(182, 'Warkocz Bereniki', 22, 'Najaśniejsze gwiazdy konstelacji to Comea Berenices, druga w kolejności Com oraz Comae Berenices', 'north', 386, 13, NULL),
	(183, 'Wielki Pies', -21, 'Potrzeba dość małej wyobraźni, by zobaczyć psa w jasnych gwiazdach Wielkiego Psa. Syriusz jest jego okiem, a beta,\ngwiazda drugiej wielkości, jest pazurem przedniej łapy. Trójkąt utworzony przez omikron2, deltę i epsilon jest zadem, a linie do ety i zety stanowią ogon i tylną nogę psa.', 'south', 380, 7, NULL),
	(184, 'Pawia', -65, 'Alfa i leżący dokładnie na południe od niej trójkąt prostokątny, zbudowany z gwiazd Bety, Delty i Epsilona, to najlepiej rozpoznawalny asteryzm w gwiazdozbiorze. Gwiazda nosi mało oryginalną nazwę Paw. Historia nadania nazwy związana jest z „Almanachem okrętowym” wydanym w 1930 przez monarchię brytyjską. W tym czasie Alfa Pavonis była jedną z dwóch spośród 57. najjaśniejszych gwiazd niemających nazwy własnej (druga to Epsilon Carinae, która została nazwana Avior). Królewskie Siły Powietrzne nalegały, aby te gwiazdy otrzymały nazwy własne, a że nie było lepszego pomysłu, nazwano najjaśniejszą gwiazdę w Pawiu od samej konstelacji.', 'south', 378, 20, NULL),
	(185, 'Żurawia', -45, 'Gwiazdozbiór jest jednym z najjaśniejszych ptaków na niebie. Gwiazdy, które składają się na współczesną konstelację Żurawia, były od starożytności łączone z ptakami. Pomimo bladości wielu gwiazd Żurawia całkiem wyraźnie tworzą one sylwetkę ptaka. Głową jest Gamma na północy, a lekko zagięta linia bladych gwiazd, prowadząca na południe przez Lambdę i Deltę do Bety, kształtuje długą szyję i ramiona. Alfa przedstawia jedno skrzydło, Jota i Theta tworzą drugie, a Epsilon i Zeta – ogon na południowym końcu.', 'south', 366, 23, NULL),
	(186, 'Wilka', -45, 'W Wilku nie ma gwiazd pierwszej wielkości, ale za to jest sporo gwiazd 2. i 3. wielkości. Nietrudno je zauważyć pomiędzy Centaurem i Skorpionem, ale jakoś mało przypominają wilka.', 'south', 334, 15, NULL),
	(187, 'Sekstantu', 0, 'Sekstant leży daleko od jasnych świateł Drogi Mlecznej i ma niewiele do zaoferowania astronomom amatorom.', 'north', 314, 10, NULL),
	(188, 'Tukana', -65, 'Gwiazdy Tukana nie bardzo przypominają jakiegokolwiek ptaka W konstelacji znajduje się zaledwie dziewięć gwiazd jaśniejszych niż 5m. Gwiazdy ?, ?, ?, ?, ?\ni ? tworzą kształt rozpoznawany przez miłośników astronomii jako latawiec. Natomiast Alfa, Gamma i Beta tworzą długi trójkąt równoramienny.', 'south', 295, 0, NULL),
	(189, 'Indianina ', -60, 'Blade gwiazdy konstelacji zawierają mnóstwo galaktyk i gwiazdę, która jest jedną z najbliższych sąsiadek Słońca. Główne gwiazdy, Alfa, Beta, Delta i Theta, tworzą długi trójkąt nie przypominający figury narysowanej przez Bayera.', 'south', 294, 22, NULL),
	(190, 'Oktanta', -85, 'Główne gwiazdy tworzą długi nierównoramienny trójkąt w pobliżu Południowego Bieguna Niebieskigo. Obszar, w którym znajduje się Oktant, jest dość pusty. Gwiazda piątej wielkości (5,42m), Sigma (?) Octantis, obecnie odległa o 63\' od południowego bieguna niebieskiego, pełni w czasach nowożytnych rolę południowej gwiazdy polarnej, stąd jej nazwa własna Polaris Australis. Nie stanowi takiego elementu orientacyjnego, jak Alfa (?) Ursae Minoris na półkuli północnej, z racji 25 razy mniejszej jasności. Dwie gwiazdy „biegunowe”, Sigma Octantis (? Oct) i Polaris (? UMi), różnią się zasadniczo pod względem jasności i odległości, ale mają jedną wspólną cechę: obydwie są pulsującymi gwiazdami zmiennymi typu F. Polaris jest cefeidą, a Sigma Octantis jest gwiazdą typu Delta Scuti, która zmienia swoją jasność o 0,03m z okresem 138 minut.', 'south', 291, 21, NULL),
	(191, 'Zająca ', -20, 'Chociaż Zając cichutko leży u stóp Oriona, to jego gwiazdy nie są całkowicie zasłonięte i można je zauważyć stosunkowo łatwo. Dwie rozbieżne linie trzech gwiazd – Delty, Alfy i Mi po stronie północnej oraz Gammy, Bety i Epsilona po południowej – tworzą szkielet wzoru. Wszystkie są trzeciej lub czwartej wielkości, a grupa bardziej przypomina róg obfitości niż zająca.', 'south', 290, 6, NULL),
	(192, 'Lutni', 40, 'Charakterystyczny równoległobok gwiazd tworzy kształt ramy niebiańskiego instrumentu. Z gwiazd, które będą w przyszłości wskazywały biegun północny, Wega – Alfa (?) Lutni o wielkości 0,03, jest zdecydowanie najjaśniejsza (piąta co do jasności na nocnym niebie). Pozostałe cztery gwiazdy, tworzące charakterystyczny trapez, należą do trzeciej i czwartej wielkości gwiazdowej. Są to kolejno: Gamma, Beta, Delta i Zeta Lyrae.', 'north', 286, 19, NULL),
	(193, 'Pucharu', -15, 'Blade gwiazdy nie bardzo mogą poruszyć wyobraźnię obserwatorów. Konstelacja składa się ze słabych gwiazd, najjaśniejsza, Delta Crateris (? Crt) ma jasność 3,56m, pozostałe – w kolejności: Gamma Crateris (? Crt), Alfa Crateris (? Crt), Beta Crateris (? Crt), ?, ? i ? Crt – są jaśniejsze niż 5m. Wymienione gwiazdy wraz z ? Crt (5,2m) tworzą kształt przypominający puchar. Ponieważ wszystkie te gwiazdy są czwartej lub piątej wielkości, więc trzeba ciemnego nieba, żeby je wyraźnie zobaczyć.', 'south', 282, 12, NULL),
	(194, 'Gołębia', -35, 'Chociaż gwiazdy konstelacji bardzo mało przypominają gołębia, to wygięta linia gwiazd trzeciej i czwartej wielkości wiodąca od Epsilon (?) przez Alfę (?), Betę (?), Gammę (?) do delty (?) jest łatwo rozpoznawalna na południe od Syriusza.', 'south', 270, 6, NULL),
	(195, 'Liska', 25, 'Lisek jest wykrojony z Drogi Mlecznej w Łabędziu pomiędzy Strzałą a betą Łabędzia. Na granicy Liska i Strzały znajduje się grupa gwiazd, układająca się w kształt haka, widoczna przez małą lunetę, nazywana też gromada Wieszak.', 'north', 268, 20, NULL),
	(196, 'Mała Niedźwiedzica', 75, 'Gwiazdy te w żaden sposób nie przypominają niedźwiedzia, bo ten musiałby składać się głównie z ogona. Tworzą natomiast kształt podobny do asteryzmu Wielkiego Wozu w Wielkiej Niedźwiedzicy i są nazywane Małym Wozem.', 'north', 256, 15, NULL),
	(197, 'Lunety', -50, 'W gwiazdozbiorze znajduje się siedem gwiazd jaśniejszych niż 5m[4]. Głównymi gwiazdami są gwiazdy czwartej wielkości Alfa i Zeta oraz gwiazda piątej wielkości Epsilon. Tworzą one mały, niemal prostokątny trójkąt na południe od Skorpiona, który celuje w niego jasną linią gwiazd ogona: Lambdą, Kappą i Jotą Skorpiona.', 'south', 252, 19, NULL),
	(198, 'Zegara', -50, 'W cichym zakątku niebiańskiej rzeki Erydan niezwracające na siebie uwagi gwiazdy Zegara zaczęły odmierzać na niebie czas. Ciemne gwiazdy tworzą długą linie wzdłuż brzegów wielkiej niebiańskiej rzeki i nie są w ogóle podobne do zegara wahadłowego. Konstelacja zaczyna się trochę na zachód od grupy gwiazd w kształcie latawca w gwiazdozbiorze Sieci, wywija się na północ przez kilka gwiazd piątej i szóstej wielkości i kończy się najjaśniejszą gwiazdą tej konstelacji – Alfa Horologii (? Hor). Jest to jedyna gwiazda czwartej wielkości w tym gwiazdozbiorze, przeciętny olbrzym typu K, znajdujący się w końcowym stadium ewolucji. Na początku był karłem klasy A, prawdopodobnie bardzo podobnym do Syriusza. Teraz, w wieku około miliarda lat, używa jako źródła energii fuzji nie tylko jąder wodoru, ale i helu. Znajduje się w odległości około 117 lat świetlnych od Słońca i jest 47 razy jaśniejszy od Słońca. Wkrótce się jeszcze bardziej rozprzestrzeni i stanie się w pełni rozwiniętym czerwonym olbrzymem.', 'south', 249, 3, NULL),
	(199, 'Malarza', -54, 'Główne gwiazdy tworzą długi, cienki, różnoboczny trójkąt na zachód od jasnej Kanopus, którą nietrudno znaleźć nawet z przedmieścia. Większość gwiazd konstelacji krąży wokół Drogi Mlecznej w jednym kierunku. Gwiazda Kapteyna jest wyjątkiem, który krąży w przeciwną stronę niż inne gwiazdy w sąsiedztwie Słońca.', 'south', 247, 6, NULL),
	(200, 'Ryba Południowa', -30, 'Najjaśniejsza gwiazda Ryby Południowej, Fomalhaut (Alfa Piscis Austrini), jest pierwszą (zachodnią) z trzech jasnych gwiazd nieba południowego ułożonych w jednej linii (pozostałe to Achernar i Kanopus), stanowiących ważny element orientacyjny dla dawnych żeglarzy.', 'south', 245, 22, NULL),
	(201, 'Wąż wodny', -70, 'Zarys konstelacji jest blady, ale można dopatrzyć się w nim podobieństwa do węża. Długi trójkąt prostokątny utworzony przez Gammę, Betę i Epsilon tworzą splątane ciało, a zakrzywiona linia gwiazd pomiędzy Deltą a Alfą reprezentuje podniesioną głowę gada gotowego do ataku.', 'south', 243, 2, NULL),
	(202, 'Pompy', -35, 'Pompa leży bardzo blisko płaszczyzny Drogi Mlecznej, a w jej tle jest sporo słabych gwiazd. Główne gwiazdy Alfa (?), Theta (?), Epsilon (?) i Jota (?), wszystkie pomiędzy czwartą a piątą wielkością gwiazdową, tworzą duży trapezoid, mało podobny do pompy powietrznej.', 'south', 239, 10, NULL),
	(203, 'Ołtarza', -54, 'Gwiazdy Ołtarza są łatwe do znalezienia, ponieważ leżą na południe od ogona Skorpiona. Dziwne jest jedynie to, że żadna z nich nie ma swojej nazwy, tym bardziej że konstelację znali już starożytni. Dwie zakrzywione linie, będące wzajemnie niemal lustrzanymi odbiciami, oznaczają boki ołtarza: Alfa (?), Beta (?), Gamma (?) i Delta (?) na zachodzie oraz Epsilon (?), Zeta (?) i eta (?) na wschodzie. Jasna Droga Mleczna, płynąca przez sąsiednie gwiazdozbiory Węgielnicy i Skorpiona, może być interpretowane jako niebiański dym ze spalonych darów.', 'south', 237, 17, NULL),
	(204, 'Mały Lew', 35, 'Gwiazdozbiór ten nie ma gwiazdy oznaczonej Alfa. Angielski astronom Francis Baily, który przyporządkowywał greckie litery do gwiazd gwiazdozbiorów, nadał drugiej pod względem jasności gwieździe oznaczenie Beta Leonis Minoris, ale przegapił jaśniejszą 46 Leonis Minoris.', 'north', 232, 10, NULL),
	(205, 'Kompasu', -30, 'Główne gwiazdy czwartej wielkości i bledsze nie mają żadnego podobieństwa do pudełka zawierającego okrągły kompas.', 'south', 221, 9, NULL),
	(206, 'Mikroskopu', -35, 'Główne gwiazdy tworzą na południe od Koziorożca odwróconą, lekko skrzywioną literę L. Wszystkie są piątej wielkości lub ciemniejsze, a cała grupa niewiele przypomina mikroskop.', 'south', 210, 21, NULL),
	(207, 'Ptak Rajski', -75, 'Rajski Ptak leży pomiędzy charakterystycznym zarysem Trójkąta Południowego a południowym biegunem niebieskim. Mały prostokątny trójkąt, utworzony przez Betę (?), Gammę (?) i Deltę (?) Rajskiego Ptaka, jest najlepiej widoczną częścią tego gwiazdozbioru, podczas gdy Alfa (?) znajduje się nieco z boku i leży w pobliżu granicy z Kameleonem. Każda z tych gwiazd jest czerwonym albo pomarańczowym olbrzymem. Nie zawiera gwiazd jaśniejszych niż trzeciej wielkości.', 'south', 206, 16, NULL),
	(208, 'Jaszczurki', 45, 'Ze względu na niewielką jasność, żadna z gwiazd nie posiada własnej nazwy. Astronomowie posługują się ich liczbowo-literowymi oznaczeniami katalogowymi. Główne gwiazdy tworzą zygzakowatą linię, która może naśladować ścieżkę pędzącej jaszczurki. Gwiazdy mają wielkość 4 i 4,5; zadziwiająco dobrze widać je na ciemnym niebie. Obserwując niebo z przedmieścia, należy posługiwać się lornetką, bo zygzak nie jest bardzo długi. Jako leżąca między spiralnymi ramionami naszej Galaktyki Jaszczurka wydaje się świecić bardzo słabo.', 'north', 201, 23, NULL),
	(209, 'Delfina', 13, 'Ta wyraźnie ukształtowana konstelacja jest blada i odległa, ale gwiazdy Delfina są łatwe do zidentyfikowania. Zwarty kształt rombu jest bardzo łatwy do znalezienia. Najjaśniejsze gwiazdy w Delfinie mają dopiero trzecią i czwartą wielkość gwiazdową.', 'north', 189, 21, NULL),
	(210, 'Kruk', -20, 'Chociaż główne gwiazdy Kruka w ogóle nie przypominają ptaka, to są bardzo dobrze widoczne na tle raczej bladego otoczenia. Główną częścią gwiazdozbioru jest wyraźny czworokąt utworzony przez Betę, Epsilon, Gammę i Deltę.', 'south', 184, 13, NULL),
	(211, 'Mały Pies', 5, 'W Małym Psie wszystkie gwiazdy oprócz Procjona i trzeciej wielkości Bety (?) są bardzo blade. Alfa Małego Psa to Procjon, ta starożytna grecka nazwa oznacza „idący przed psem”. Na półkuli północnej wschodzi tuż przed Syriuszem.', 'north', 182, 8, NULL),
	(212, 'Złota Ryba', -60, 'W gwiazdach konstelacji trudno dopatrzyć się jakiejkolwiek istoty morskiej. Tworzą długą pokręconą linię od Gammy na północy przez Alfę, Zetę do Bety na południu, w pobliżu Wielkiego Obłoku Magellana.', 'south', 179, 5, NULL),
	(213, 'Korona Północna', 30, 'Alphecca, Alfa (?) Korony Północnej, jest członkiem Gromady Ruchomej w Wielkiej Niedźwiedzicy (Collinder 285), która to grupa zawiera też pięć centralnych gwiazd asteryzmu Wielkiego Wozu i rozmaite gwiazdy Wielkiej Niedźwiedzicy, Małego Lwa i Smoka. Jest to gromada najbliższa Układowi Słonecznemu, chociaż są kontrowersje, czy ta rzadka, szeroko rozrzucona grupa może być uważana za prawdziwą gromadę otwartą, skoro jej własna grawitacja nie jest w stanie utrzymać grupy w całości.', 'north', 178, 16, NULL),
	(214, 'Węgielnicy', -50, 'Granice gwiazdozbioru zmieniały się od XVIII wieku, dlatego najjaśniejsze gwiazdy wchodzące poprzednio w jego skład wcielono do Skorpiona – zostały oznaczone N i H Sco.', 'south', 165, 16, NULL),
	(215, 'Góry Stołowej', -80, 'Najjaśniejsze gwiazdy widoczne są tylko jako blade plamki piątej wielkości, niezbędne są więc dobre warunki, by je zobaczyć. Cztery główne gwiazdy, Alfa, Gamma, Eta i Beta tworzą trapez za Wielkim Obłokiem Magellana. Alfa Men jest najbledszą na niebie gwiazdą Alfa.', 'south', 153, 6, NULL),
	(216, 'Ryba Latająca', -70, 'Najlepiej rozpoznawalną częścią konstelacji jest szeroki trapez podobnie wyglądających gwiazd znajdujący się w połowie drogi pomiędzy jasną gwiazdą Miaplacidusem w Kilu i Wielkim Obłokiem Magellana. Gwiazdy Alfa i Beta leżą poza tym asteryzmem, są blisko Miaplacidusa. W konstelacji najjaśniejszą gwiazdą jest Gamma, jeżeli liczyć oba składniki razem, a nie Alfa. Również Beta jest jaśniejsza od Alfy. W gwiazdozbiorze brak jasnych gwiazd. Najjaśniejsza Beta Volantis (? Vol) ma wielkość 3,77m, a tylko pięć kolejnych gwiazd jest jaśniejsza niż 5m. Na niebie można je rozpoznać jako dwa połączone ze sobą trójkąty: ?, ? i ? Vol oraz ?, ? i ? Vol.', 'south', 141, 8, NULL),
	(217, 'Muchy', -70, 'Pięć gwiazd trzeciej i czwartej wielkości tworzy łatwo rozpoznawalny asteryzm „piątki karo”, który jest składnikiem Muchy. Cztery z nich – wyjątek stanowi Delta – znajdują się w odległości około 300 lat świetlnych od Słońca, chociaż fizycznie nie są ze sobą w żaden sposób związane.', 'south', 138, 12, NULL),
	(218, 'Trójkąta', 32, 'Gwiazdy tworzące zarys Trójkąta są dość jasne. Należy odszukać na niebie Almach (? And), następnie podążając na południe nad gwiazdozbiorem Barana, odnaleźć gwiazdy należące do konstelacji Trójkąta.', 'north', 132, 2, NULL),
	(219, 'Kameleona', -80, 'Główne gwiazdy konstelacji tworzą długi cienki kształt rombu, której dłuższe boki wyciągnięte są wzdłuż linii wschód-zachód. Środek figury leży na południe od punktu pomiędzy głównymi gwiazdami Muchy i Miaplacidusem, jasną gwiazdą w Kilu. Żadna z gwiazd nie jest szczególnie jasna, ale pięć najjaśniejszych z nich ma wielkość pomiędzy 4,05 i 4,45.', 'south', 132, 11, NULL),
	(220, 'Korona Południowa', -40, 'Żadna z gwiazd konstelacji nie jest jasna, choć ich zbliżona jasność i regularne położenie sprawiają, że łatwo ją rozpoznać. Jeśli do kilku gwiazd półksiężyca dodać Thetę (?), Kappę (?) i Lambdę (?), to na nowoczesnych „patyczkowych” mapach dostrzegalny jest cały okrąg.', 'south', 128, 19, NULL),
	(221, 'Rylca', -40, 'Ciemne i rozproszone gwiazdy konstelacji nie ułatwiają znalezienia figury, która miałyby przedstawiać. Jest wśród nich zaledwie jedna gwiazda czwartej wielkości i kilka piątej wielkości. Beta (?) i Alfa (?) Caeli tworzą trzon gwiezdnego rylca, wskazującego na południe, na gwiazdozbiory Złotej Ryby i Sieci.', 'south', 125, 5, NULL),
	(222, 'Sieci', -60, 'Podstawowe gwiazdy sieci są blade i tworzą mały wyraźny asteryzm w kształcie latawca na zachód od Wielkiego Obłoku Magellana.', 'south', 114, 4, NULL),
	(223, 'Trójkąt Południowy', -65, 'Gwiazdozbiór, jeden z dwóch trójkątów na niebie, jest łatwiejszy do znalezienia niż jego odpowiednik z półkuli północnej.', 'south', 110, 16, NULL),
	(224, 'Tarczy', -10, 'Zawiera 18 gwiazd jaśniejszych niż 6m, leży jednak w szczególnie bogatym w gwiazdy obszarze Drogi Mlecznej między Orłem a Strzelcem. Gwiazdy te są blade i czasami trudne do znalezienia z powodu jasnego tła Drogi Mlecznej. Alfa, Beta, Gamma i Zeta tworzą asteryzm w kształcie litery Y.', 'south', 109, 19, NULL),
	(225, 'Cyrkla', -62, 'W obrębie Cyrkla znajdują się zaledwie cztery gwiazdy jaśniejsze niż 5m. Trzy główne gwiazdy Cyrkla tworzą długi wąski trójkąt równoramienny, który wygląda jak niemal złożony cyrkiel, nieco na wschód od Alfa Centaura. Alfa Cyrkla jest najjaśniejszą gwiazdą konstelacji, która przy tym ma bardzo dziwne widmo.', 'south', 93, 15, NULL),
	(226, 'Strzały', 19, 'W Strzale nie ma wiele ciekawych obiektów, które można obejrzeć małymi instrumentami. Blade gwiazdy przekonująco przedstawiają zarys strzały, jest to praktycznie jedyny kształt, jaki można z nich sporządzić. Leżące obok siebie Alfa i Beta tworzą lotki, a linia poprowadzona przez Deltę i Gammę stanowią korpus zakończony ostrzem-gwiazdą Etą.', 'north', 80, 20, NULL),
	(227, 'Źrebięcia', 7, 'Źrebię to najmniejszy po Krzyżu Południa gwiazdozbiór na niebie. W odróżnieniu od obficie rozgwieżdżonego Krzyża Południa, który jest najmniejszym gwiazdozbiorem, Źrebię składa się jedynie z kilku bladych galaktyk i zbioru gwiazd podwójnych. Mały trapezoid gwiazd czwartej i piątej wielkości jest wyraźny, ale najlepiej oglądać go w dobrych warunkach. Można też użyć lornetki, bo trapezoid ma zaledwie 5° łuku w najdłuższym wymiarze.', 'north', 72, 21, NULL),
	(228, 'Krzyża Południa', -60, 'Krzyż Południa to najmniejszy gwiazdozbiór na niebie, ale widoczny jest na niemal najjaśniejszym fragmencie Drogi Mlecznej i ma zdecydowanie ponadprzeciętną liczbę jasnych gwiazd. Zaczynając od świetlistego Acruxa, jasność gwiazd maleje, poruszając się zgodnie z ruchem wskazówek zegara przez Betę, Gammę, Deltę i Epsilon Krzyża Południa.', 'south', 68, 13, NULL);
/*!40000 ALTER TABLE `constellations` ENABLE KEYS */;

-- Zrzut struktury tabela starsdb.stars
CREATE TABLE IF NOT EXISTS `stars` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `rectascensionh` tinyint(4) NOT NULL DEFAULT 0,
  `rectascensionm` tinyint(4) NOT NULL DEFAULT 0,
  `rectascensions` tinyint(4) NOT NULL DEFAULT 0,
  `declinationh` tinyint(4) NOT NULL DEFAULT 0,
  `declinationm` tinyint(4) NOT NULL DEFAULT 0,
  `declinations` tinyint(4) NOT NULL DEFAULT 0,
  `radial_speed` varchar(20) DEFAULT NULL,
  `distance` varchar(20) DEFAULT NULL,
  `brightness` varchar(20) DEFAULT NULL,
  `star_type` varchar(50) DEFAULT NULL,
  `mass` varchar(20) DEFAULT NULL,
  `greek_symbols` varchar(1) DEFAULT NULL,
  `constellation_id` int(11) NOT NULL,
  `discaverer_id` int(11) DEFAULT NULL,
  `confirmed` varchar(3) NOT NULL DEFAULT 'NO',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `name` (`name`),
  KEY `DK` (`discaverer_id`),
  KEY `CK` (`constellation_id`) USING BTREE,
  CONSTRAINT `CK` FOREIGN KEY (`constellation_id`) REFERENCES `constellations` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `DK` FOREIGN KEY (`discaverer_id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=98 DEFAULT CHARSET=utf8mb3;

-- Zrzucanie danych dla tabeli starsdb.stars: ~20 rows (około)
DELETE FROM `stars`;
/*!40000 ALTER TABLE `stars` DISABLE KEYS */;
INSERT INTO `stars` (`Id`, `name`, `rectascensionh`, `rectascensionm`, `rectascensions`, `declinationh`, `declinationm`, `declinations`, `radial_speed`, `distance`, `brightness`, `star_type`, `mass`, `greek_symbols`, `constellation_id`, `discaverer_id`, `confirmed`) VALUES
	(74, 'Gamma Hydrae', 13, 18, 55, -23, 10, 17, '-4.74', '133.0', '109.0', 'żółty olbrzym', '3.1', 'γ', 141, NULL, 'YES'),
	(75, 'Psi Hydrae', 13, 9, 3, -23, 7, 5, '-17.2', '231.0', '56.0', 'Hyper giants', '0.0', 'ψ', 141, NULL, 'YES'),
	(76, 'Beta Hydrae', 11, 52, 54, -33, 54, 29, '-1.0', '310.0', '257.0', 'olbrzym', '3.36', 'β', 141, NULL, 'YES'),
	(77, 'Ksi Hydrae', 11, 33, 0, -31, 51, 27, '-4.9', '129.0', '60.0', 'żółty olbrzym', '3.31', 'ξ', 141, NULL, 'YES'),
	(78, 'Ni Hydrae', 10, 49, 37, -16, 11, 37, '-1.37', '143.7', '156.0', 'olbrzym', '2.0', 'ν', 141, NULL, 'YES'),
	(79, 'Mu Hydrae', 10, 26, 5, -16, 50, 9, '6.0', '234.0', '332.0', 'olbrzym', '0.0', 'μ', 141, NULL, 'YES'),
	(80, 'Lambda Hydrae', 10, 10, 35, -12, 21, 14, '19.4', '109.0', '39.8', 'pomarańczowy olbrzym', '1.0', 'λ', 141, NULL, 'YES'),
	(81, 'Alphard', 9, 27, 35, -8, 39, 31, '-4.27', '180.3', '780.0', 'olbrzym', '3.03', 'α', 141, NULL, 'YES'),
	(82, 'Tau 1 Hydrae', 9, 9, 9, -2, 46, 8, '10.85', '57.0', '3.369', 'nieokreślona', '1.2', 'τ', 141, NULL, 'YES'),
	(83, 'Tau 2 Hydrae', 9, 31, 59, -1, 11, 5, '3.9', '520.0', '285.0', 'biały karzeł', '0.0', 'τ', 141, NULL, 'YES'),
	(84, 'Theta Hydrae', 9, 14, 22, 2, 18, 54, '-10.7', '115.0', '52.0', 'biały karzeł', '2.52', 'θ', 141, NULL, 'YES'),
	(85, 'Zeta Hydrae', 8, 55, 24, 5, 56, 44, '22.3', '167.2', '138.0', 'żółty olbrzym', '3.0', 'ζ', 141, NULL, 'YES'),
	(86, 'Ro Hydrae', 8, 48, 26, 5, 50, 16, 'nan', '337.0', '242.0', 'nieokreślona', '0.0', 'ρ', 141, NULL, 'YES'),
	(87, 'Epsilon Hydrae', 8, 46, 47, 6, 25, 8, '36.4', '129.3', '52.0', 'żółty olbrzym', '2.5', 'ε', 141, NULL, 'YES'),
	(88, 'Eta Hydrae', 8, 43, 13, 3, 23, 55, 'nan', '590.0', '2.7', 'nieokreślona', '7.0', 'η', 141, NULL, 'YES'),
	(89, 'Sigma Hydrae', 8, 38, 45, 3, 20, 29, '-14.34', '373.0', '295.0', 'olbrzym', '3.07', 'σ', 141, NULL, 'YES'),
	(90, 'Delta Hydrae', 8, 37, 39, 5, 42, 14, '4.1', '160.0', '42.7', 'nieokreślona', '2.88', 'δ', 141, NULL, 'YES'),
	(91, 'Upsilon 1 Hydrae', 9, 51, 29, -14, 50, 48, '-14.0', '264.0', '162.0', 'olbrzym', '3.33', 'υ', 141, NULL, 'YES'),
	(92, 'Upsilon 2 Hydrae', 10, 5, 7, -13, 3, 53, '24.3', '314.0', '182.0', 'subolbrzym', '3.29', 'υ', 141, NULL, 'YES'),
	(96, 'test', 1, 1, 1, 1, 1, 1, '', '', '', 'Giants', '', NULL, 142, 1, 'YES');
/*!40000 ALTER TABLE `stars` ENABLE KEYS */;

-- Zrzut struktury tabela starsdb.user
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `surname` varchar(100) NOT NULL,
  `login` varchar(100) NOT NULL,
  `password` varchar(1000) NOT NULL,
  `email` varchar(100) NOT NULL,
  `rules` varchar(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `login` (`login`)
) ENGINE=InnoDB AUTO_INCREMENT=115 DEFAULT CHARSET=utf8mb3;

-- Zrzucanie danych dla tabeli starsdb.user: ~2 rows (około)
DELETE FROM `user`;
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT INTO `user` (`id`, `name`, `surname`, `login`, `password`, `email`, `rules`) VALUES
	(1, 'admin', 'admin', 'admin', 'b\'6j\\xa0lS\\xfe}3\\x9f:\\xc4\\xfc\\x8a\\xa4\\x93%b\\x8b\\x13n\\x93\\xf9g1\\x08\\xa85\\x95\\xe9\\x94\\x9f\\xc1\'', 'admin@admin.com', 'administrator'),
	(114, 'user', 'user', 'user', '1234567890', 'ghdgdg@dsag.com', 'użytkownik');
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
